version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      # - linode
    environment:
      DB_URL: mongo:27017
      DB_NAME: rw_socket
   

  mongo:
    image: mongo:latest
    # env_file:
    #   - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
