version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DB_URL: mongo:27017
      DB_NAME: rw_socket
    volumes:
      - .:/usr/src/app # Mounts the current directory to /usr/src/app in the container
      - /usr/src/app/node_modules # Ensures node_modules are not overridden

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
